### ISSUE TITLE
Альтернативные карточки для управления

### ISSUE THREAD

**Issue by vasokot** [vakio-ru/vakio_base_smart#1]
Подскажите - как добавить эту интеграцию на панель, если конфиг через yaml с помощью альтернативных карточек ?
Текущий вид очень неудобен, хочется просто регулировать с панели, не открывая отдельных окон

Пример удобного интерфейса: https://github.com/artem-sedykh/mini-humidifier

**Comment by Anti-Sh** [comment]
Добрый день! Изучим вопрос и дадим вам знать!

Подскажите, удобно ли вам будет использовать стандартные компоненты HomeAssistant для управления?
Например в таком виде (кнопки имеют не конечный вид):
![image](https://github.com/vakio-ru/vakio_base_smart/assets/59616866/f8f6d591-c27d-4dd4-8860-98fbddb41b30)

Интересует ваше мнение)

**Comment by vasokot** [comment]
Здравствуйте! 
Прошу прощения за долгий ответ.
Конечно, если бы это была одна карточка было бы интереснее. Но можно и так попробовать :)

**Comment by Rupunx** [comment]
> Добрый день! Изучим вопрос и дадим вам знать!
> 
> Подскажите, удобно ли вам будет использовать стандартные компоненты HomeAssistant для управления? Например в таком виде (кнопки имеют не конечный вид): 
> 
> Интересует ваше мнение)


Пришлите пожалуйста yaml-код для карточки
