### ISSUE TITLE
Не добавляется второе устройство

### ISSUE THREAD

**Issue by Alkamenos** [vakio-ru/vakio_base_smart#2]
В коде зашит id из-за этого второе устройство добавляется с тем же id и игнорируется homeassistant

**Comment by EstebanSteffovski** [comment]
У меня так же. Второе устройство не добавляется

**Comment by xSirrioNx** [comment]
То же самое

**Comment by Anti-Sh** [comment]
@Alkamenos , @EstebanSteffovski , @xSirrioNx 
Доброго времени суток, извините за задержки. Опубликовал новую версию. Теперь несколько устройств одной модели могут работать одновременно без каких либо проблем.
