### ISSUE TITLE
Не добавляется прибор в HA

### ISSUE THREAD

**Issue by NIkimih** [vakio-ru/vakio_base_smart#3]
Захожу по ip на прибор, меняю mqtt сервер на свой, сохраняю настройки, но после обнровления страницы сервер для подключения обратно переходит на Vakio.  Версия прошивки на устройстве 1.1.3. В чем может быть проблема?

**Comment by Anti-Sh** [comment]
Добрый день, отправьте снимок экрана сервисной страницы устройства после изменения параметров (не применяя их).

**Comment by NIkimih** [comment]
Отправил вам видео.
--
Отправлено из Mail.ru для Android воскресенье, 11 февраля 2024г., 16:18 +03:00 от NIkolay O.  ***@***.*** :

>Добрый день, отправьте снимок экрана сервисной страницы устройства после изменения параметров (не применяя их).
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

К этому письму приложены ссылки на следующие файлы:

1. 20240211_160549.mp4 (51.4 Мб)

Ссылка для скачивания файлов: https://cloud.mail.ru/stock/bMuL8x6cNGa91A1EpG3mKpvp

Файлы будут храниться до 09.08.2024

**Comment by Anti-Sh** [comment]
Попробуйте на второй странице не нажимать "Сохранить".
Каков результат?
Если можно, в таком же формате

**Comment by NIkimih** [comment]
Результат тот же самый. Видео надо или на слово поверите?)

**Comment by Anti-Sh** [comment]
Верю)
Передам в конструкторский отдел. По обновлению статуса уведомлю

**Comment by NIkimih** [comment]
Спасибо. Еще написал через приложение Vakio в поддержку. Если нужна будет доп инфа, пишите, на связи.

**Comment by NIkimih** [comment]
Добрый день. Обновили прошивку на рекуператорах. Настройки брокера сохраняются, но через HA все равно не могу управлять.
![1](https://github.com/vakio-ru/vakio_base_smart/assets/56358416/86ec4da8-0a85-48bf-9acf-e5381b817fd3)
![2](https://github.com/vakio-ru/vakio_base_smart/assets/56358416/2eb8d48f-87fd-4cf6-a2c1-96a9965e042b)
![3](https://github.com/vakio-ru/vakio_base_smart/assets/56358416/0eba8fd5-2235-4dd0-8f6b-076c4b9b253e)
![4](https://github.com/vakio-ru/vakio_base_smart/assets/56358416/cb11eb52-a4f6-4056-900e-48029a4c285b)

**Comment by Anti-Sh** [comment]
Судя по фотографии, прибор не подключен к Wi-Fi. Вы указали актуальные данные сети?

**Comment by NIkimih** [comment]
Добрый день. Прибор так же подключен к сети и я могу к нему обратиться по его Ip адресу.

**Comment by Anti-Sh** [comment]
Добрый день, извините за задержку.
Подскажите, у вас есть возможность с помощью какого либо клиента (например, [MqttX](https://mqttx.app/)), подключиться к вашему брокеру и выполнить следующие действия:
1.  Подписаться на топик '#'.
2.  Изменить состояние прибора с помощью кнопок на лицевой панели прибора, например.
3.  Посмотреть, пришли ли сообщения.

Исходя из результата, определим дальнейшие действия)

**Comment by NIkimih** [comment]
Добрый день. 
Возможность будет. На выходных сделаю, результат пришлю.

**Comment by WoodenLoony** [comment]
Тоже были проблемы с подключением. У меня проблема решилась примерно так...
Адрес роутера поменял на 192.168.0.1, был не стандартный
Без логина и пароля в журнале Mosquitto broker писал received null username or password for unpwd check
С логином и паролем username password писал disconnected, not authorised.
С логином и паролем таким же как и в Mosquitto broker поставлено - соединился.
При этом описанное мне не помогало, когда устройство не было сопряжено с приложением на смартфоне. (Было удалено)
И еще, при настройке Прибора, он "постоянно" переставал загружать страницу настройки или не сохранял настройки или сохранял, но не все и т.п..
