### ISSUE TITLE
Ошибка ValueError: None is not in list

### ISSUE THREAD

**Issue by Alkamenos** [vakio-ru/vakio_base_smart#4]
Получаю ошибку при выполнении

```alias: тест
description: ""
triggers: []
conditions: []
actions:
  - action: fan.set_preset_mode
    metadata: {}
    data:
      preset_mode: Приток
    target:
      entity_id:
        - fan.base_smart
        - fan.base_smart_2
mode: single
```

<img width="1222" alt="image" src="https://github.com/user-attachments/assets/ea831e80-7c71-4411-9c20-e0950d82ee82">

**Comment by Anti-Sh** [comment]
Добрый день!
Вы указали читаемое название режима, а не системное.

Для корректной работы используйте `inflow`.

Список значений режимов:
```
"inflow"  # Приток
"inflow_max"  # Приток MAX
"recuperator"  # Рекуперация лето
"winter"  # Рекуперация зима
"outflow"  # Вытяжка
"outflow_max"  # Вытяжка MAX
"night"  # Ночной
```

Информацию по значениям остальных параметров можно найти в файле [custom_components/vakio_base_smart/const.py](https://github.com/vakio-ru/vakio_base_smart/blob/main/custom_components/vakio_base_smart/const.py)

**Comment by Alkamenos** [comment]
Так тоже не работает 
<img width="625" alt="image" src="https://github.com/user-attachments/assets/2fd68a8a-1fea-4d7e-9ac8-6fead6fdf495">

**Comment by Alkamenos** [comment]
У вас в документации так 
<img width="949" alt="image" src="https://github.com/user-attachments/assets/ae5a7b8c-3b4e-4629-bae8-8fe307de22aa">

**Comment by Alkamenos** [comment]
Может не доходит из автоматизации? Как-то проверить можно?

**Comment by Alkamenos** [comment]
Была проблемма с обновлениями версий, корректное значение "Приток", как в документации. Закрываю
